### ISSUE TITLE
Loading issue when loading Segment with require

### ISSUE THREAD

**Issue by pcothenet** [segment-integrations/analytics.js-integration-madkudu#1]
Getting this error on app.madkudu.com (which uses require.js)

```
Mismatched anonymous define() module: function (){return require("1")}
```

Looks very similar to https://github.com/segment-integrations/analytics.js-integration-amplitude/blob/master/lib/index.js#L62

Attempting the same fix and will create a PR.

**Comment by hankim813** [comment]
Thanks for the quick [fix](https://github.com/MadKudu/analytics.js-integration-madkudu/pull/1)!
